# -*- coding: utf-8 -*-
"""Untitled85.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16olIKzETQhSegV4oPuuUxyeMxivX6KHI
"""



import numpy as np

class LinearRegressionScratch:

    def __init__(self, learning_rate=0.01, iterations=1000):
        self.learning_rate = learning_rate
        self.iterations = iterations

    def fit(self, X, y):
        self.m, self.n = X.shape

        y = y.reshape(self.m,)

        self.w = np.zeros(self.n)
        self.b = 0

        for i in range(self.iterations):
            y_pred = self.predict(X)

            # gradients
            dw = (-2 / self.m) * np.dot(X.T, (y - y_pred))
            db = (-2 / self.m) * np.sum(y - y_pred)

            # update
            self.w -= self.learning_rate * dw
            self.b -= self.learning_rate * db

            # optional: print loss
            if i % 100 == 0:
                loss = np.mean((y_pred - y)**2)
                print(f"Iteration {i}  Loss: {loss:.4f}")

    def predict(self, X):
        return np.dot(X, self.w) + self.b