# -*- coding: utf-8 -*-
"""Untitled86.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4Gm7G1-is01QdTfr8we8rmeH23X5d8G
"""

import numpy as np

class Logistic_Regression:

    def __init__(self, learning_rate=0.01, no_of_iterations=1000):
        self.learning_rate = learning_rate
        self.no_of_iterations = no_of_iterations

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))   # optional: add numerical stability

    def fit(self, X, Y):
        self.m, self.n = X.shape
        self.w = np.zeros(self.n)
        self.b = 0

        self.X = X
        self.Y = Y

        for _ in range(self.no_of_iterations):
            self.update_weights()

    def update_weights(self):
        Z = self.X.dot(self.w) + self.b
        Y_hat = self.sigmoid(Z)

        dw = (1/self.m) * np.dot(self.X.T, (Y_hat - self.Y))
        db = (1/self.m) * np.sum(Y_hat - self.Y)

        self.w -= self.learning_rate * dw
        self.b -= self.learning_rate * db

    def predict_proba(self, X):
        return self.sigmoid(X.dot(self.w) + self.b)

    def predict(self, X):
        Y_pred = self.predict_proba(X)
        return np.where(Y_pred > 0.5, 1, 0)